const {test}=require('node:test'),assert=require('node:assert/strict');
const p=require('./cloud-probe.cjs');
const fixture=()=>Array.from({length:65},(_,i)=>({date:new Date(Date.UTC(2026,5,1+i)).toISOString().slice(0,10),open:3,high:3.2,low:2.9,close:3.1,volume:10000}));
test('Tencent volume is normalized from lots to shares',()=>{const b=fixture(),text=JSON.stringify({data:{sh510880:{day:b.map(x=>[x.date,x.open,x.close,x.high,x.low,x.volume/100])}}});assert.deepEqual(p.bars(text,'tencent'),b);});
test('duplicate and malformed OHLC fail closed',()=>{const a=fixture().map(x=>({...x,day:x.date}));a[1].day=a[0].day;assert.throws(()=>p.bars(JSON.stringify(a),'sina'));a[1].day='2026-06-02';a[1].high=2;assert.throws(()=>p.bars(JSON.stringify(a),'sina'));});
test('comparison requires fresh dates and 60 matching days',()=>{const a=fixture(),asof=a.at(-1).date;assert.equal(p.compare(a,a,asof).matchedDays,60);assert.throws(()=>p.compare(a,a.slice(0,-1),asof));const b=structuredClone(a);b.at(-1).close+=.001;assert.throws(()=>p.compare(a,b,asof));});
test('volume quantization tolerance is limited',()=>{const a=fixture(),b=structuredClone(a),asof=a.at(-1).date;b.at(-1).volume+=50;assert.equal(p.compare(a,b,asof).matchedDays,60);b.at(-1).volume++;assert.throws(()=>p.compare(a,b,asof));});
test('Shanghai close boundary, holiday and unknown year',()=>{const c={year:2026,ranges:[{from:'2026-10-01',to:'2026-10-07'}]};assert.equal(p.expectedClose(c,new Date('2026-09-25T06:59:00Z')),'2026-09-24');assert.equal(p.expectedClose(c,new Date('2026-09-25T07:00:00Z')),'2026-09-25');assert.equal(p.expectedClose(c,new Date('2026-10-05T09:00:00Z')),'2026-09-30');assert.throws(()=>p.expectedClose(c,new Date('2027-01-01T09:00:00Z')));});
test('broken auxiliary sources are not accepted as no dividends/holidays',()=>{assert.throws(()=>p.dividends('<html>error</html>'));assert.throws(()=>p.calendar('<html>error</html>'));assert.throws(()=>p.managerCheck('',[]));});

const policy=require('./calendar-policy.cjs');
const official=()=>'<strong>2026年休市安排</strong><table>'+[
 ['元旦',1,1,1,3],['春节',2,15,2,23],['清明',4,4,4,6],['劳动',5,1,5,5],['端午',6,19,6,21],['中秋',9,25,9,27],['国庆',10,1,10,7]
].map(([name,m,d,m2,d2])=>`<tr><td>${name}</td><td>${m}月${d}日（测试）至${m2}月${d2}日（测试）休市</td></tr>`).join('')+'</table>';
const priorOf=r=>({calendarCache:r.cache,sources:{calendar:r.source}});
test('calendar official success caches 24h without repeated network requests',async()=>{const now=new Date('2026-09-25T08:00:00Z');let calls=0;const request=async()=>{calls++;return {text:official()};};const x=await policy.acquireCalendar(null,now,request);assert.equal(x.error,null);assert.equal(x.source.status,'ok');assert.equal(x.cache.days['2026-09-25'],false);const y=await policy.acquireCalendar(priorOf(x),new Date(+now+600000),request);assert.equal(calls,1);assert.equal(y.source.status,'cached');assert.equal(y.cache.verifiedAt,x.cache.verifiedAt);});
test('403 fallback uses audited days, backs off 1h/2h and does not invent verification',async()=>{const now=new Date('2026-09-25T08:00:00Z');let calls=0;const request=async()=>{calls++;throw Error('HTTP 403');};const x=await policy.acquireCalendar(null,now,request);assert.equal(x.error,null);assert.equal(x.source.status,'fallback');assert.equal(x.source.coverageThrough,'2026-12-31');assert.equal(x.source.nextCheckAt,'2026-09-25T09:00:00.000Z');const y=await policy.acquireCalendar(priorOf(x),new Date(+now+600000),request);assert.equal(calls,1);assert.equal(y.cache.verifiedAt,x.cache.verifiedAt);const z=await policy.acquireCalendar(priorOf(y),new Date(+now+3600000),request);assert.equal(calls,2);assert.equal(z.source.nextCheckAt,'2026-09-25T11:00:00.000Z');});
test('calendar conflict blocks, remains blocked after transport failure, and can recover only from matching official page',async()=>{const now=new Date('2026-09-25T08:00:00Z');const x=await policy.acquireCalendar(null,now,async()=>({text:official().replace('9月25日','9月24日')}));assert.match(x.error,/冲突/);assert.equal(x.source.blocked,true);const y=await policy.acquireCalendar(priorOf(x),new Date(+now+3600000),async()=>{throw Error('HTTP 403');});assert.ok(y.error);assert.equal(y.source.status,'blocked');const z=await policy.acquireCalendar(priorOf(y),new Date(+now+86400000),async()=>({text:official()}));assert.equal(z.error,null);assert.equal(z.source.blocked,false);});
test('unknown year, corrupt cache, malformed official response and stale cache fail closed',async()=>{const fail=async()=>{throw Error('HTTP 403');};const x=await policy.acquireCalendar(null,new Date('2027-01-04T08:00:00Z'),fail);assert.ok(x.error);const y=await policy.acquireCalendar(null,new Date('2026-10-03T08:00:00Z'),fail);assert.match(y.error,/7天/);const z=await policy.acquireCalendar(null,new Date('2026-09-25T08:00:00Z'),async()=>({text:'<html>not a calendar</html>'}));assert.ok(z.error);const days={...require('./calendar-2026.json')};delete days['2026-09-25'];const invalid=await policy.acquireCalendar({calendarCache:{days,verifiedAt:'2026-09-25T07:00:00Z'}},new Date('2026-09-25T08:00:00Z'),fail);assert.match(invalid.error,/缺日/);});
test('blocked calendar cannot advance published strategy and preserves old confirmed result',async()=>{const {published}=require('./build.cjs');const previous={confirmed:{asof:'2026-09-24',model:{state:{shares:0}}}};const state=await policy.acquireCalendar(null,new Date('2026-09-25T08:00:00Z'),async()=>({text:'broken'}));const out=published(previous,new Date('2026-09-25T08:00:00Z'),{calendarState:state},{calendar:state.source});assert.equal(out.status,'error');assert.deepEqual(out.confirmed,previous.confirmed);assert.equal(out.calendarCache.verifiedAt,state.cache.verifiedAt);});
